### ISSUE TITLE
Unable use GraphQLTimeoutContext in context in ApolloServer-v4

### ISSUE THREAD

**Issue by simpyparveen** [rromadhoni/graphql-timeout-middleware#2]
I tried using it in following code and aparently does not work:

`         app.use(
            '/graphql',
            cors<cors.CorsRequest>({
                origin: [...],
                methods: "POST"
            }),
            json({
                limit: "50mb"
            }),
            expressMiddleware(myapolloServer, {
                 context: async ({ req }) => {
                 ... 
                 ....
                 const context = { user, token, cookies: cookie, timeout: GraphQLTimeoutMiddleware.context() };
                        return {context};
                }`
                
                
                **This throws an INTERNAL ERROR: Context creation failed: Cannot read properties of undefined (reading 'code')**

**Comment by simpyparveen** [comment]
Context creation failed: Cannot read properties of undefined (reading 'context')

**Comment by simpyparveen** [comment]
@rrmdn This is working:
```
                        const mycontext = GraphQLTimeoutMiddleware.context
                            ? GraphQLTimeoutMiddleware.context(10, 1) : {};
                            
```
But it does not invoke any timeouts.                             
                     What is the significance of adding values GraphQLTimeoutMiddleware.context(10, 1):
```
                     GraphQLTimeoutContext {
                        timeoutInMs: 15000, // what does this do and can we change it
                          timeoutDecrementInMs: 50, // what does this do and can we change it
                          executionStartTimestamp: 1697033479225, // calculated on runtime
                          parentTypes: []
                        }
```
                         
I tried to decrease it but it by `GraphQLTimeoutMiddleware.context(10, 1)`, yet it throws no errors. Do I have to call them in each resolver ? Or it can take care of any resolver for my apolloserver:

```
const MyTimeoutContext = GraphQLTimeoutMiddleware.context
                            ? GraphQLTimeoutMiddleware.context(10, 1)
                            : {};
                        // console.log("MyTimeoutContext:", MyTimeoutContext);
                        const mycontext = { myuser, mytoken, cookies: mycookie, timeout: MyTimeoutContext };
```

**Comment by rrmdn** [comment]
@simpyparveen you don't need to do anything beyond what's shown in the example, and regarding the options:

1. `timeoutInMs` is the total time you can wait for the whole query/mutation to be done, exceeding this timeout will throw an error.
2. `timeoutDecrementInMs`, the middleware will expect less timeout for deeper resolvers, [how less](https://github.com/rrmdn/graphql-timeout-middleware/blob/master/src/GraphQLTimeoutContext.js#L22)? `timeoutDecrementInMs * depth` less.

with the options of `timeoutInMs: 1500; timeoutDecrementInMs: 100`, it will:

```graphql
query getComments {
  # wait for this to resolve for 1500ms
  comments {
    id
    content
    # wait for this to resolve for 1400ms
    replies {
      id
      content
      # wait for this to resolve for 1300ms
      user: {
        id
        name
      }
    }
  }
}
```
